location_url: "https://hhnk.lizard.net/api/v4/timeseries/"

timeseries_url: "https://hhnk.lizard.net/api/v4/timeseries/{}/events/"
start_date: "2025-02-01"
end_date: "2025-06-01"
headers:
  Content-Type: "application/json"

pump_names: ["Rg. Blauwe Keet", "Rg. Kooypunt", "Rg. Julianadorp"]
data_codes: ["WNS2369.h", "P.radar.1h"]
join_keys: ["timestamp", "pumpcode"]
primary_keys: ["ds", "pumpcode"]

neuralprophet_rename: {"P.radar.1h":"precipitation", "WNS2369.h":"y", "timestamp":"ds"}
numerical_features: ["ds","precipitation"]
target: ["ds","y"]

train_test_split: 0.8

dev_catalog: "mlops_dev"
dev_schema: "jbaars"

vacations_file: "/Volumes/mlops_dev/jbaars/vacations/vakanties.csv"
pump_features_file: "/Volumes/mlops_dev/jbaars/feature_table_data/pump_features.csv"

experiment_name: /Shared/sewage_pumps/
